version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  
  api:
    build: .
    ports:
      - 4000:4000
    environment:
      MONGO_ATLAS_PASSWORD: Sandeep
      JWT_ACCESS_KEY: Sandy
      JWT_REFRESH_KEY: Karthik
      MONGODB_URI: mongodb+srv://Sandeep:Sandeep@node-medicareapp.dpgqpzu.mongodb.net/MedicareData?retryWrites=true&w=majority
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}